name: Deploy PHP to gh-pages

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install PHP
        run: composer install
      - name: Build PHP
        run: php bin/build
      - name: Deploy to gh-pages
        run: git subtree push --prefix public gh-pages master
