name: Deploy PHP to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install PHP
        run: sudo apt install php
      - name: Build PHP
        run: php index.php
      - name: Deploy to GitHub Pages
        run: gh pages upload --dir public
